export type Team = keyof typeof teams;

export const teams = {
  1: {
    id: 1,
    abbreviaton: "ATL",
    city: "Atlanta",
    name: "Hawks",
    full_name: "Atlanta Hawks",
    logo_path: "/teams/ATL_logo.svg",
  },
  2: {
    id: 2,
    abbreviaton: "BOS",
    city: "Boston",
    name: "Celtics",
    full_name: "Boston Celtics",
    logo_path: "/teams/BOS_logo.svg",
  },
  3: {
    id: 3,
    abbreviaton: "BKN",
    city: "Brooklyn",
    name: "Nets",
    full_name: "Brooklyn Nets",
    logo_path: "/teams/BKN_logo.svg",
  },
  4: {
    id: 4,
    abbreviaton: "CHA",
    city: "Charlotte",
    name: "Hornets",
    full_name: "Charlotte Hornets",
    logo_path: "/teams/CHA_logo.svg",
  },
  5: {
    id: 5,
    abbreviaton: "CHI",
    city: "Chicago",
    name: "Bulls",
    full_name: "Chicago Bulls",
    logo_path: "/teams/CHI_logo.svg",
  },
  6: {
    id: 6,
    abbreviaton: "CLE",
    city: "Cleveland",
    name: "Cavaliers",
    full_name: "Cleveland Cavaliers",
    logo_path: "/teams/CLE_logo.svg",
  },
  7: {
    id: 7,
    abbreviaton: "DAL",
    city: "Dallas",
    name: "Mavericks",
    full_name: "Dallas Mavericks",
    logo_path: "/teams/DAL_logo.svg",
  },
  8: {
    id: 8,
    abbreviaton: "DEN",
    city: "Denver",
    name: "Nuggets",
    full_name: "Denver Nuggets",
    logo_path: "/teams/DEN_logo.svg",
  },
  9: {
    id: 9,
    abbreviaton: "DET",
    city: "Detroit",
    name: "Pistons",
    full_name: "Detroit Pistons",
    logo_path: "/teams/DET_logo.svg",
  },
  10: {
    id: 10,
    abbreviaton: "GSW",
    city: "Golden State",
    name: "Warriors",
    full_name: "Golden State Warriors",
    logo_path: "/teams/GSW_logo.svg",
  },
  11: {
    id: 11,
    abbreviaton: "HOU",
    city: "Houston",
    name: "Rockets",
    full_name: "Houston Rockets",
    logo_path: "/teams/HOU_logo.svg",
  },
  12: {
    id: 12,
    abbreviaton: "IND",
    city: "Indiana",
    name: "Pacers",
    full_name: "Indiana Pacers",
    logo_path: "/teams/IND_logo.svg",
  },
  13: {
    id: 13,
    abbreviaton: "LAC",
    city: "Los Angeles",
    name: "Clippers",
    full_name: "Los Angeles Clippers",
    logo_path: "/teams/LAC_logo.svg",
  },
  14: {
    id: 14,
    abbreviaton: "LAL",
    city: "Los Angeles",
    name: "Lakers",
    full_name: "Los Angeles Lakers",
    logo_path: "/teams/LAL_logo.svg",
  },
  15: {
    id: 15,
    abbreviaton: "MEM",
    city: "Memphis",
    name: "Grizzlies",
    full_name: "Memphis Grizzlies",
    logo_path: "/teams/MEM_logo.svg",
  },
  16: {
    id: 16,
    abbreviaton: "MIA",
    city: "Miami",
    name: "Heat",
    full_name: "Miami Heat",
    logo_path: "/teams/MIA_logo.svg",
  },
  17: {
    id: 17,
    abbreviaton: "MIL",
    city: "Milwaukee",
    name: "Bucks",
    full_name: "Milwaukee Bucks",
    logo_path: "/teams/MIL_logo.svg",
  },
  18: {
    id: 18,
    abbreviaton: "MIN",
    city: "Minnesota",
    name: "Timberwolves",
    full_name: "Minnesota Timberwolves",
    logo_path: "/teams/MIN_logo.svg",
  },
  19: {
    id: 19,
    abbreviaton: "NOP",
    city: "New Orleans",
    name: "Pelicans",
    full_name: "New Orleans Pelicans",
    logo_path: "/teams/NOP_logo.svg",
  },
  20: {
    id: 20,
    abbreviaton: "NYK",
    city: "New York",
    name: "Knicks",
    full_name: "New York Knicks",
    logo_path: "/teams/NYK_logo.svg",
  },
  21: {
    id: 21,
    abbreviaton: "OKC",
    city: "Oklahoma City",
    name: "Thunder",
    full_name: "Oklahoma City Thunder",
    logo_path: "/teams/OKC_logo.svg",
  },
  22: {
    id: 22,
    abbreviaton: "ORL",
    city: "Orlando",
    name: "Magic",
    full_name: "Orlando Magic",
    logo_path: "/teams/ORL_logo.svg",
  },
  23: {
    id: 23,
    abbreviaton: "PHI",
    city: "Philadelphia",
    name: "76ers",
    full_name: "Philadelphia 76ers",
    logo_path: "/teams/PHI_logo.svg",
  },
  24: {
    id: 24,
    abbreviaton: "PHX",
    city: "Phoenix",
    name: "Suns",
    full_name: "Phoenix Suns",
    logo_path: "/teams/PHX_logo.svg",
  },
  25: {
    id: 25,
    abbreviaton: "POR",
    city: "Portland",
    name: "Trail Blazers",
    full_name: "Portland Trail Blazers",
    logo_path: "/teams/POR_logo.svg",
  },
  26: {
    id: 26,
    abbreviaton: "SAC",
    city: "Sacramento",
    name: "Kings",
    full_name: "Sacramento Kings",
    logo_path: "/teams/SAC_logo.svg",
  },
  27: {
    id: 27,
    abbreviaton: "SAS",
    city: "San Antonio",
    name: "Spurs",
    full_name: "San Antonio Spurs",
    logo_path: "/teams/SAS_logo.svg",
  },
  28: {
    id: 28,
    abbreviaton: "TOR",
    city: "Toronto",
    name: "Raptors",
    full_name: "Toronto Raptors",
    logo_path: "/teams/TOR_logo.svg",
  },
  29: {
    id: 29,
    abbreviaton: "UTA",
    city: "Utah",
    name: "Jazz",
    full_name: "Utah Jazz",
    logo_path: "/teams/UTA_logo.svg",
  },
  30: {
    id: 30,
    abbreviaton: "WAS",
    city: "Washington",
    name: "Wizards",
    full_name: "Washington Wizards",
    logo_path: "/teams/WAS_logo.svg",
  },
};
