import Head from "next/head";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  console.log(session);

  async function handleSignOut() {
    const { error } = await supabase.auth.signOut();
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello world</h1>
        {session ? (
          <button className="btn" onClick={handleSignOut}>
            Sign Out
          </button>
        ) : null}
      </main>
      <footer></footer>
    </div>
  );
}
